name: ipycolorful-dev
channels:
  - conda-forge
dependencies:
  # https://anaconda.org/conda-forge/nodejs?version=14.18.3
  - nodejs=14.18.3
  - yarn=1.22.17
  - python=3.7.12
  - jupyterlab=3.2.5
  # https://anaconda.org/conda-forge/jupyter-packaging?version=0.7.9
  # https://github.com/jupyter/jupyter-packaging/tree/0.7.9
  - jupyter-packaging=0.7.9
  # https://anaconda.org/conda-forge/black-jupyter?version=22.1.0
  - black-jupyter=22.1.0
  - twine=3.6.0
  # https://anaconda.org/conda-forge/python-build?version=0.7.0
  # https://anaconda.org/conda-forge/build?version=0.7.0
  # https://github.com/mgedmin/check-manifest/blob/master/setup.py#L61
  - python-build=0.7.0
  # https://anaconda.org/conda-forge/setuptools?version=58.0.4
  - setuptools=58.0.4
  # https://anaconda.org/conda-forge/check-manifest?version=0.47
  - check-manifest=0.47
  - pip:
      # https://github.com/asottile/setup-cfg-fmt
      - setup-cfg-fmt==1.20.0
